### ISSUE TITLE
platforms/ios/DNSCryptApp/config.xml file missing?

### ISSUE THREAD

**Issue by jedisct1** [s-s/dnscloak#1]
Hi,

I tried to compile DNSCloak, but it stopped here:

```text
> org.techcultivation.dnscloak@2.2.1 prepare:dev /Users/j/src/dnscloak
> cordova prepare ios

Unhandled error. ('Parsing /Users/j/src/dnscloak/platforms/ios/DNSCryptApp/config.xml failed')
```

And sure enough, there is no `config.xml` file in this directory.

Is it expected?

Thanks in advance.

**Comment by s-s** [comment]
My bad, should work now. Just rerun `npm run build`

**Comment by jedisct1** [comment]
Thank you!

It's crashing on start, complaining about a null URL, but I'm gonna try to figure out what's going on.

**Comment by s-s** [comment]
I guess this may be related to the unexisting application group (a shared directory between the app and network extension). In general you need the following artifacts:
1. Bundle identifier for the app, i.e. “foo.bar.baz” (default “org.techcultivation.dnscloak”);
2. Bundle identifier for network extension = app’s bundle ID + “.DNSCryptAppExt”;
3. Application group with identifier “group.” + app’s bundle ID, and with access for both app and network extension.
(I would suggest replacing all occurrences of “org.techcultivation.dnscloak” with your bundle ID in project directory and then registering an app group)
