### ISSUE TITLE
Has been abandoned?

### ISSUE THREAD

**Issue by michael1900** [s-s/dnscloak#17]
Hi, is it possible to update with all last changes?

**Comment by holderad** [comment]
Yes, it has been abandoned. I have moved myself, my family, and our company to NextDNS.

Check it out at https://nextdns.io

It's built and maintained by the director of engineering at Netflix and the former Head of Mobile & TV at Dailymotion. It is endorsed by the lead of Google's Jigsaw and the designer of the Twitter interface.

I have to say that I was skeptical and worried, but it is so impressive and works so fast, I have moved past my own cobbled together systems. When NextDNS does start charging, I'll be first in line to pay. The granular control and speed on mobile is fantastic. Not having to maintain, trouble shoot, and provide tech support for my own system: priceless.

**Comment by jedisct1** [comment]
Not abandoned at all. Not only it is opensource, but the last testflight version was released 2 days ago.

Your message looks like spam. If you've been paid to spam forums and other projects, this discredits them more than anything else.

**Comment by holderad** [comment]
Not spam. Just trying to be helpful. I wrote the original Abandoned? thread. There was no response for months. I don’t know how to use TestFlight. I’m a n00b.

Chill out a little Frank. I used your DNScrypt a long while, but it got too much for me to maintain as the sole support for my family and business. Others may be in my shoes and looking for alternatives. I can’t write code but can speak up when something has worked for me. I was only trying to be helpful. Sorry if I offended anyone.

**Comment by evilvibes** [comment]
Trying to be helpful is fine but you need to understand most of these "DNScrypt" projects are hobbies for people. They do not ask for money and work on them on there free time.

**Comment by michael1900** [comment]
> Your message looks like spam. If you've been paid to spam forums and other projects, this discredits them more than anything else.


Man, are you serious? "Paid to spam forums and ..." What a movie! Where did you see this nonsense?
Really, are you serious?

I have only written a question. Nothing more.

**Comment by michael1900** [comment]
What is the code to try last testflight version?

**Comment by evilvibes** [comment]
> > Your message looks like spam. If you've been paid to spam forums and other projects, this discredits them more than anything else.
> 
> Man, are you serious? "Paid to spam forums and ..." What a movie! Where did you see this nonsense?
> Really, are you serious?
> 
> I have only written a question. Nothing more.

@jedisct1 and me were not replying to the message you posted some other user made a odd post and then he seems to have deleted his post.

**Comment by s-s** [comment]
> What is the code to try last testflight version?

`https://testflight (dot) apple (dot) com (slash) join (slash) RlMeZBo7`

Project is not abandoned, but I’m extremely short on spare time due to my current life situation. Hope to have more time within several months. 
Current TestFlight beta contains most recent changes and I’ll try to push latest ones today or tomorrow. AppStore’s release is delayed for some time, as I need to rebuild artworks (quite time consuming).

**Comment by michael1900** [comment]
> > What is the code to try last testflight version?
> 
> `https://testflight (dot) apple (dot) com (slash) join (slash) RlMeZBo7`
> 
> Project is not abandoned, but I’m extremely short on spare time due to my current life situation. Hope to have more time within several months.
> Current TestFlight beta contains most recent changes and I’ll try to push latest ones today or tomorrow. AppStore’s release is delayed for some time, as I need to rebuild artworks (quite time consuming).

My testflight app will end in few days, what i need to do? There will be a new version?
