### ISSUE TITLE
DNSCryptThread - MacOS

### ISSUE THREAD

**Issue by omody** [s-s/dnscloak#18]
Assuming you can compile the framework for MacOS what would be the proper way to implement DNSCryptThread as packettunnel provider on the MacOS 
When I use it as is on a Mac I am not sure but it isn’t starting...
Any guidance would be appreciated on how to the dnscrypt framework for MacOS

**Comment by omody** [comment]
When running from inside a MacOS app
[2020-01-31 10:16:59] [NOTICE] dnscrypt-proxy
[2020-01-31 10:16:59] [NOTICE] Network connectivity detected
[2020-01-31 10:16:59] [NOTICE] dnscrypt-proxy (unknown)
[2020-01-31 10:16:59] [NOTICE] Firefox workaround initialized
[2020-01-31 10:16:59] [FATAL] listen udp 127.0.0.1:53: bind: permission denied

Is there way to request elevated access via code in MacOS app?

**Comment by omody** [comment]
In the PacketTunnelProvider in the NetworkExtension I tried to launch the thread just like in the iOS app but seeing an error in the console
Sandbox: MyAppName(7485) deny(1) network-outbound*:53

When I tried to run in the main app I got the error I previously pasted.
[2020-01-31 10:16:59] [FATAL] listen udp 127.0.0.1:53: bind: permission denied

**Comment by s-s** [comment]
Where can I obtain your modifications to the source code (as required by MPL-2.0) so I can run them and check your issue? I’m not a theorist and not used to tell fortunes.

**Comment by omody** [comment]
Thanks for getting back to me... I made some modification to the go mobile compiler using the suggestion here
https://github.com/golang/go/issues/13310
https://github.com/golang/mobile/commit/27e1b66f2aabbd2abe32bd8cf7e316cb9f9f9371?diff=unified

**Comment by s-s** [comment]
Where can I obtain your modifications to DNSCloak sources?

**Comment by s-s** [comment]
Oh, nice! Catched! :)

Let me explain the situation for everyone. OP is a person who takes FOSS iOS works and posts them into AppStore as proprietary paid/monetized apps (will not post his profile link to avoid advertisement). Most of original works (DNSCloak, Brave Browser, Firefox) are covered by MPL-2.0, which requires to distribute source code modifications to covered work as well. Unfortunately, he doesn't.

Now he wants an extra work from me to spread his market, I guess? @omody, right? How we would share the revenue? :) Should I escalate this to copyright infringement report to Apple or you will follow MPL-2.0 requirements to distribute modifications? I'm talking about your blue-icon content blocker (utilizes DNSCloak parts), purple-icon browser (Firefox), another purple-icon browser (Brave).

PS: You haven't surprised me with gomobile modifications. As you can see - I'm quite "familiar" with it. Your original issue was solved about a year ago. ;)

**Comment by jedisct1** [comment]
Oh, nice catch @s-s and thanks for the explanations.

That kind of behavior is disgusting (and a good justification for having chosen the MPL license). Hard to avoid, though, and the situation is far worse on the Android Play Store, where you never know if what you are installing is legit or a repacked version.
