### ISSUE TITLE
Add dismail.de

### ISSUE THREAD

**Issue by StarPicard** [s-s/dnscloak#19]
Hey, dismail.de should provide DNS over HTTPS, could you please add it to the list?
https://dismail.de/info.html#dns

Thanks!

**Comment by s-s** [comment]
As far as I see it provides DNS over TLS only, which is not supported by dnscrypt-proxy.
However, DNSCloak utilizes the list of public DNSCrypt and DoH servers by default, which is located and maintained here - https://github.com/DNSCrypt/dnscrypt-resolvers.
You may address it's maintaners to add a server there and it will appear in DNSCloak too.
