### ISSUE TITLE
Support for query_meta?

### ISSUE THREAD

**Issue by eterry1388** [s-s/dnscloak#20]
Trying to add `query_meta` in the config file, but it seems doing so makes it so the vpn fails to start. I can't seem to get it to output any logs either, even on `debug` setting.

**Comment by eterry1388** [comment]
After some research, it seems the current release of `dnscloak` is on `dnsdist 2.0.19`, and support for `query_meta` wasn't added until `dnsdist 2.0.26`.

**Comment by s-s** [comment]
Works as intended on latest beta:
`https://testflight (dot) apple (dot) com (slash) join (slash) RlMeZBo7`
AppStore release is a little delayed.

**Comment by eterry1388** [comment]
Totally works on the beta version. Thank you!
