### ISSUE TITLE
Testflight dnsCloak expired 26/10/20

### ISSUE THREAD

**Issue by privacy-advo** [s-s/dnscloak#33]
Hi,
please update the testflight for dnsCloak. It completly stopped working and one had to fall back to the AppStore version with the old dnscrypt version (e.g. no CNAME filtering).

Thanks in advance

**Comment by s-s** [comment]
Hi,

Thanks for the reporting. Very strange, I’ve pushed an update several days ago.

Please, check TestFlight again — I have touched, should be available now.

**Comment by privacy-advo** [comment]
Thank you. It worked. It stopped working yesterday morning. Fixed now. It's possible to reinstall the beta.

Maybe you have some time to give me a feedback on issue 26:
https://github.com/s-s/dnscloak/issues/26

Thanks
