### ISSUE TITLE
Feature request: automatically update blocklist.

### ISSUE THREAD

**Issue by TacoBoy2318** [s-s/dnscloak#46]
Is it possible to let DNScloak automatically update blocklist? That way it will function like a mobile pihole. Is it difficult to implement? Thanks.

**Comment by gitthehubs** [comment]
That would be usefull. The dnscrypt proxy used by dnscloak has links to blacklists:
https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Public-blacklists

**Comment by s-s** [comment]
FYI nor DNSCloak, nor dnscrypt-proxy are adblockers. Won't work for many reasons. You may implement this as a part of dnscrypt-proxy and I'll port it here.
