### ISSUE TITLE
“Hide VPN Icon in Statusbar” gone in latest update (2.2.2)

### ISSUE THREAD

**Issue by frontiergd** [s-s/dnscloak#50]
The toggle for “showIcon” has been removed from the UI for some reason. This bug has seemed to happen after the 2.2.2 update. I tried adding “showIcon = false” to the config, but that just gives me a unsupported key error.

**Comment by s-s** [comment]
Not a bug, but a random Apple requirement to remove it during update review. Review process is always a lottery. Will try to bring it back in the next update, somewhere under Advanced settings and definitely renamed.
